config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  category_values = %w[chinese italian japanese french belgian]

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: category_values }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_restaurant_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.select :category, %w[chinese italian japanese french belgian] %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <div class="row">
    <div class="col-4">
      <ul class="list-group">
      <% @restaurants.each do |restaurant| %>
        <li class="list-group-item d-flex justify-content-between"><%= link_to restaurant.name, restaurant_path(restaurant), class: "text-decoration-none"  %><button class="btn btn-secondary"><%= link_to "Add a review", new_restaurant_review_path(restaurant), class: "text-decoration-none text-white"  %></button></li>
      <% end %>
      </ul>
      <button class="btn btn-primary"><%= link_to 'Add a restaurant', new_restaurant_path, class: "text-white text-decoration-none" %></button>
    </div>

  </div>

</div>

app/views/restaurants/new.html.erb
<div class="container">
  <%= render 'restaurant_form' %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <ul>
    <li><%= @restaurant.address %></li>
    <li><%= @restaurant.phone_number %></li>
    <li><%= @restaurant.category.capitalize %></li>
  </ul>
  <div class="row justify-content-left">
    <div class="col-2">
      <h2>Reviews</h2>
    </div>
    <div class="col-2">
      <button class="inline-block btn btn-secondary"><%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "text-decoration-none text-white"  %></button>
    </div>
  </div>

  <ul>
    <% @reviews.each do |review| %>
      <% if review.restaurant_id == @restaurant.id  %>
        <li>Rating: <%= review.rating %> | <%= review.content %></li>
      <% end  %>
    <% end  %>
  </ul>
</div>

app/views/reviews/_review_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Add review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <%= render 'review_form' %>
</div>